jwt:
  secret: 'rQ:jx1VB5PWdMPPBEDko1L+HAHFrWlfC6c.i8g^g#'

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tvmrezadb?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    password: password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   
